//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spring_Generator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spring_Generator.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.5.
        /// </summary>
        internal static string SPG_12_105 {
            get {
                return ResourceManager.GetString("SPG_12_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string SPG_12_12 {
            get {
                return ResourceManager.GetString("SPG_12_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.5.
        /// </summary>
        internal static string SPG_12_155 {
            get {
                return ResourceManager.GetString("SPG_12_155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16.
        /// </summary>
        internal static string SPG_12_16 {
            get {
                return ResourceManager.GetString("SPG_12_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17.
        /// </summary>
        internal static string SPG_12_17 {
            get {
                return ResourceManager.GetString("SPG_12_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.5.
        /// </summary>
        internal static string SPG_12_185 {
            get {
                return ResourceManager.GetString("SPG_12_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.5.
        /// </summary>
        internal static string SPG_12_195 {
            get {
                return ResourceManager.GetString("SPG_12_195", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SPG_12_20 {
            get {
                return ResourceManager.GetString("SPG_12_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.5.
        /// </summary>
        internal static string SPG_12_225 {
            get {
                return ResourceManager.GetString("SPG_12_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.5.
        /// </summary>
        internal static string SPG_12_235 {
            get {
                return ResourceManager.GetString("SPG_12_235", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.5.
        /// </summary>
        internal static string SPG_12_245 {
            get {
                return ResourceManager.GetString("SPG_12_245", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string SPG_12_25 {
            get {
                return ResourceManager.GetString("SPG_12_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string SPG_8_14 {
            get {
                return ResourceManager.GetString("SPG_8_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string SPG_8_15 {
            get {
                return ResourceManager.GetString("SPG_8_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.5.
        /// </summary>
        internal static string SPG_8_185 {
            get {
                return ResourceManager.GetString("SPG_8_185", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string SPG_8_18D {
            get {
                return ResourceManager.GetString("SPG_8_18D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string SPG_8_19 {
            get {
                return ResourceManager.GetString("SPG_8_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string SPG_8_19D {
            get {
                return ResourceManager.GetString("SPG_8_19D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SPG_8_20 {
            get {
                return ResourceManager.GetString("SPG_8_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string SPG_8_20D {
            get {
                return ResourceManager.GetString("SPG_8_20D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string SPG_8_21 {
            get {
                return ResourceManager.GetString("SPG_8_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        internal static string SPG_8_21D {
            get {
                return ResourceManager.GetString("SPG_8_21D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string SPG_8_22 {
            get {
                return ResourceManager.GetString("SPG_8_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.5.
        /// </summary>
        internal static string SPG_8_225 {
            get {
                return ResourceManager.GetString("SPG_8_225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string SPG_8_22D {
            get {
                return ResourceManager.GetString("SPG_8_22D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string SPG_8_23 {
            get {
                return ResourceManager.GetString("SPG_8_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        internal static string SPG_8_23D {
            get {
                return ResourceManager.GetString("SPG_8_23D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string SPG_8_24 {
            get {
                return ResourceManager.GetString("SPG_8_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        internal static string SPG_8_24D {
            get {
                return ResourceManager.GetString("SPG_8_24D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.5.
        /// </summary>
        internal static string SPG_8_255 {
            get {
                return ResourceManager.GetString("SPG_8_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.5.
        /// </summary>
        internal static string SPG_8_255D {
            get {
                return ResourceManager.GetString("SPG_8_255D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string SPG_8_25D {
            get {
                return ResourceManager.GetString("SPG_8_25D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.5.
        /// </summary>
        internal static string SPG_8_265 {
            get {
                return ResourceManager.GetString("SPG_8_265", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.5.
        /// </summary>
        internal static string SPG_8_265D {
            get {
                return ResourceManager.GetString("SPG_8_265D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        internal static string SPG_8_26D {
            get {
                return ResourceManager.GetString("SPG_8_26D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.5.
        /// </summary>
        internal static string SPG_8_275 {
            get {
                return ResourceManager.GetString("SPG_8_275", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string SPG_8_27D {
            get {
                return ResourceManager.GetString("SPG_8_27D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string SPG_8_28 {
            get {
                return ResourceManager.GetString("SPG_8_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.5.
        /// </summary>
        internal static string SPG_8_285 {
            get {
                return ResourceManager.GetString("SPG_8_285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.5.
        /// </summary>
        internal static string SPG_8_285D {
            get {
                return ResourceManager.GetString("SPG_8_285D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string SPG_8_28D {
            get {
                return ResourceManager.GetString("SPG_8_28D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29.5.
        /// </summary>
        internal static string SPG_8_295 {
            get {
                return ResourceManager.GetString("SPG_8_295", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string SPG_8_30D {
            get {
                return ResourceManager.GetString("SPG_8_30D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string SPG_8_31D {
            get {
                return ResourceManager.GetString("SPG_8_31D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32.
        /// </summary>
        internal static string SPG_8_32D {
            get {
                return ResourceManager.GetString("SPG_8_32D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33.5.
        /// </summary>
        internal static string SPG_8_335D {
            get {
                return ResourceManager.GetString("SPG_8_335D", resourceCulture);
            }
        }
    }
}
